# Generated by Django 6.0 on 2026-01-10 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "human_id",
                    models.CharField(
                        blank=True, default="", max_length=32, unique=True
                    ),
                ),
                ("start_at_utc", models.DateTimeField()),
                ("end_at_utc", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("HOLD", "HOLD"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PICKED_UP", "PICKED_UP"),
                            ("RETURNED", "RETURNED"),
                            ("CANCELED", "CANCELED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("hold_expires_at_utc", models.DateTimeField(blank=True, null=True)),
                ("notes_customer", models.TextField(blank=True, default="")),
                ("notes_staff", models.TextField(blank=True, default="")),
                ("currency", models.CharField(default="CZK", max_length=8)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="fleet.branch",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("UPDATED", "UPDATED"),
                            ("STATUS_CHANGED", "STATUS_CHANGED"),
                            ("HOLD_PLACED", "HOLD_PLACED"),
                            ("HOLD_RESET", "HOLD_RESET"),
                            ("HOLD_EXPIRED", "HOLD_EXPIRED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PICKED_UP", "PICKED_UP"),
                            ("RETURNED", "RETURNED"),
                            ("CANCELED", "CANCELED"),
                            ("VEHICLE_CHANGED", "VEHICLE_CHANGED"),
                            ("TIME_CHANGED", "TIME_CHANGED"),
                            ("PRICE_CHANGED", "PRICE_CHANGED"),
                            ("BRANCH_CHANGED", "BRANCH_CHANGED"),
                            ("CONFLICT_DETECTED", "CONFLICT_DETECTED"),
                            ("IDP_REPLAYED", "IDP_REPLAYED"),
                        ],
                        max_length=32,
                    ),
                ),
                ("at_utc", models.DateTimeField()),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("HOLD", "HOLD"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PICKED_UP", "PICKED_UP"),
                            ("RETURNED", "RETURNED"),
                            ("CANCELED", "CANCELED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("HOLD", "HOLD"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PICKED_UP", "PICKED_UP"),
                            ("RETURNED", "RETURNED"),
                            ("CANCELED", "CANCELED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("delta_json", models.JSONField(blank=True, default=dict)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["vehicle", "start_at_utc", "end_at_utc"],
                name="reservation_vehicle_6d61ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["branch", "start_at_utc", "end_at_utc"],
                name="reservation_branch__442068_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_f1a03a_idx"),
        ),
        migrations.AddIndex(
            model_name="reservationevent",
            index=models.Index(
                fields=["reservation", "at_utc"], name="reservation_reserva_b07ea7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservationevent",
            index=models.Index(
                fields=["event_type"], name="reservation_event_t_c33d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservationevent",
            index=models.Index(
                fields=["request_id"], name="reservation_request_800093_idx"
            ),
        ),
    ]
