# Generated by Django 6.0 on 2026-01-15 12:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name="vehicle",
        #    name="plate",
        #),
        migrations.CreateModel(
            name="VehiclePlate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plate", models.CharField(max_length=32)),
                ("is_current", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plates",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["plate"], name="fleet_vehic_plate_bd6a6d_idx"),
                    models.Index(
                        fields=["vehicle", "is_current"],
                        name="fleet_vehic_vehicle_4a7abe_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("plate",),
                        name="uniq_current_plate_global",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("vehicle",),
                        name="uniq_current_plate_per_vehicle",
                    ),
                ],
            },
        ),
    ]
