# Generated by Django 6.0 on 2026-01-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_migrate_vehicle_plate_to_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="plate",
        ),
    ]
