# Generated by Django 6.0 on 2026-01-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingquote",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="pricingquoteitem",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pricing.pricingquote",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingquote",
            index=models.Index(
                fields=["reservation", "status"], name="pricing_pri_reserva_ef075b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingquoteitem",
            index=models.Index(
                fields=["quote", "code"], name="pricing_pri_quote_i_7fbc8a_idx"
            ),
        ),
    ]
